export const languageObject = {
  en: {
    arrow: "right",
    navItems: [
      "Home",
      "News",
      "Business",
      "Energy",
      "Opinion",
      "Life",
      "Video",
      "Coronavirus",
    ],
    captionText: [
      'How do you condemn the "forced displacement" of the inhabitants of Kherson and Zaporozhye',
      "Night demonstrations in Iranian cities... Security confronts protesters with live bullets",
      "NATO Secretary General: We will not accept Iran's plans to provide Russia with drones and missiles",
      "Israeli warplanes bombed several sites in central Gaza",
    ],
    mainSectionAsideElementParagraph: [
      "Biden advances campaign in bid to save Democrats",
      "A few hours separated the British economy from a comprehensive financial meltdown in October",
      "Musk cancels “remote work” and plans a mass massacre of employees.",
      "For the fourth time, a Chinese missile gets out of control and hits the ground within hours.",
    ],
    mainSectionAsideElementSpan: [
      "American Elections",
      "Britain",
      "Twitter",
      "Judiciary",
      "Special",
      "Iran Protests",
      "Pakistan",
      "Special",
      "Iran Protests",
      "Pakistan",
      "Pakistan",
      "Pakistan",
    ],
    sectionSecondTitle: ["News", "More", "Saudi Arabia", "Markets"],
    sectionSecondArticleElementParagraph: [
      "Egyptian Prince: My success in world cinema does not contradict my presence in the Egyptian arena",
      "30 people were killed and injured in a terrible traffic accident in southern Egypt",
      "In an electoral speech on the West Coast, Biden pledges to “liberate” Iran.",
      "Khan accuses Pakistani PM of trying to assassinate him, Washington warns of violence",
      "Egyptian Prince: My success in world cinema does not contradict my presence in the Egyptian arena",
      "30 people were killed and injured in a terrible traffic accident in southern Egypt",
      "In an electoral speech on the West Coast, Biden pledges to “liberate” Iran.",
      "Khan accuses Pakistani PM of trying to assassinate him, Washington warns of violence",
    ],
    thirdSectionHeaderRight: ["Most Read", "trending topics"],
    thirdSectionHeaderLeft: ["Today", "This Week"],
    thirdSectionArticleElementInfosTitle: [
      "You have only 7 seconds to find the treasure hidden in the depths of the sea.",
      "Surprise.. Sherine Abdel Wahab in her home!",
      "After his problem with Shakira, Pique announces his retirement from football.",
      "You have only 7 seconds to find the treasure hidden in the depths of the sea.",
      "Surprise.. Sherine Abdel Wahab in her home!",
      "After his problem with Shakira, Pique announces his retirement from football.",
    ],
    thirdSectionArticleElementInfosBottomRight: [
      "Last",
      "Culture and Art",
      "Global Sport",
      "Last",
      "Culture and Art",
      "Global Sport",
    ],
    thirdSectionArticleElementInfosBottomLeft: [
      "51,122 Views",
      "34,902 Views",
      "34,902 Views",
      "51,122 Views",
      "34,902 Views",
      "34,902 Views",
    ],
    fourthSectionArticleTopRightParagraph: [
      "Saudi Arabia: Thwart the smuggling of more than 3.2 million Captagon pills",
      "Auction of paintings drawn by people with autism raises 6.5 million riyals",
      "Saudi Arabia: Thwart the smuggling of more than 3.2 million Captagon pills",
      "Auction of paintings drawn by people with autism raises 6.5 million riyals",
    ],
    fourthSectionArticleBottomTopParagraph: [
      "Two injured in a fire that broke out in a fuel tanker in Madinah",
      "Saudi Arabia strongly condemns the assassination attempt on Imran Khan.",
      "Two injured in a fire that broke out in a fuel tanker in Madinah",
      "Saudi Arabia strongly condemns the assassination attempt on Imran Khan.",
    ],
    navItemHeader: [
      "News",
      "Saudi Arabia",
      "Sport",
      "Mix",
      "Arabiya TV",
      "Articles",
      "Last",
      "Broadcast",
    ],
    language: "Language",

    embeddedNavItemLinks: [
      "Arabs and The World",
      " Arabian Gulf",
      "Sport",
      "Syria",
      "Egypt",
      "America",
      "Iran",
      "Iraq",
      "News",
      "Fourth flyer",
      "Sport",
      "Opinios",
      "Saudi Sport",
      "Arabian Sport",
      "Global Sport",
      "Other Sports",
      "Opinios",
      "Health",
      "Technology",
      "Social Media",
      "Style",
      "Science",
      "Arabiya Video",
      "Arabiya Social Media",
      "Arabian Shows",
      "Political Opinions",
      "Athlete Opinions",
      "Saudi Opinions",
    ],
    upSpan: ["Back to top"],

    copyRight: ["All Rights Reserved for Arabiya Network - 2022"],
  },
  ar: {
    navItems: [
      "الرئيسية",
      "الأخبار",
      "السعودية",
      "أسواق",
      "رياضة",
      "العربية TV",
      "البرامج",
      "منوعات",
      "مقالات",
      "الأخيرة",
      "فيروس كورونا",
      "برودكاست",
    ],
    language: "اللغة",
    captionText: [
      'كيف تدين "التهجير القسري" لسكان خيرسون وزابوروجيا',
      "تظاهرات ليلية في مدن إيرانية.. والأمن يواجه المحتجين بالرصاص الحي",
      "أمين عام الناتو: لن نقبل خطط إيران لتزويد روسيا بمسيرات وصواريخ",
      "الطائرات الإسرائيلية تقصف عدة مواقع في وسط غزة",
    ],
    arrow: "left",

    mainSectionAsideElementParagraph: [
      "بايدن يتقدم حملته الانتخابية في محاولة لإنقاذ الديموقراطيين",
      "ساعات قليلة فصلت الاقتصاد البريطاني عن انهيار مالي شامل بأكتوبر",
      'ماسك يلغي "العمل عن بعد" ويخطط لمجزرة جماعية بالموظفين',
      "للمرة الرابعة.. صاروخ صيني يخرج عن السيطرة ويرتطم بالأرض خلال ساعات",
    ],
    mainSectionAsideElementSpan: [
      "الانتخابات الأمريكية",
      "بريطانيا",
      "تويتر",
      "القضاء",
      "خاص",
      "احتجاجات إيران",
      "باكستان",
      "خاص",
      "احتجاجات إيران",
      "باكستان",
      "باكستان",
      "باكستان",
    ],
    sectionSecondTitle: ["الأخبار", "المزيد", "السعودية", "أسواق"],
    sectionSecondArticleElementParagraph: [
      "أمير مصري: نجاحي بالسينما العالمية لا يتعارض مع تواجدي بالساحةالمصرية",
      "مصرع وإصابة 30 شخصا في حادث سير مروع جنوب مصر",
      'في خطاب انتخابي بالساحل الغربي.. بايدن يتعهد "بتحيرير" إيران',
      "خان يتهم رئيس الوزراء الباكستاني بمحاولة اغتياله وواشنطن تحذر من العنف",
      "أمير مصري: نجاحي بالسينما العالمية لا يتعارض مع تواجدي بالساحة المصرية",
      "مصرع وإصابة 30 شخصا في حادث سير مروع جنوب مصر",
      'في خطاب انتخابي بالساحل الغربي.. بايدن يتعهد "بتحيرير" إيران',
      " خان يتهم رئيس الوزراء الباكستاني بمحاولة اغتياله وواشنطن تحذر من العنف",
      "",
    ],
    thirdSectionHeaderRight: ["الأكثر قراءة", "مواضيع شائعة"],
    thirdSectionHeaderLeft: ["اليوم", "الأسبوع"],
    thirdSectionArticleElementInfosTitle: [
      "أمامك 7 ثوان فقط للعثور على الكنز المخفي في أعماق البحر",
      "!مفاجأة.. شيرين عبدالوهاب في منزلها",
      "بعد مشكلته مع شاكيرا.. بيكيه يعلن إعتزاله كرة القدم",
      "أمامك 7 ثوان فقط للعثور على الكنز المخفي في أعماق البحر",
      "!مفاجأة.. شيرين عبدالوهاب في منزلها",
      "بعد مشكلته مع شاكيرا.. بيكيه يعلن إعتزاله كرة القدم",
    ],
    thirdSectionArticleElementInfosBottomRight: [
      "الأخيرة",
      "ثقافة وفن",
      "رياضة عالمية",
      "الأخيرة",
      "ثقافة وفن",
      "رياضة عالمية",
    ],
    thirdSectionArticleElementInfosBottomLeft: [
      "51,122 مشاهدة",
      "34,902 مشاهدة",
      "مشاهدة 34,902",
      "51,122 مشاهدة",
      "مشاهدة 34,902",
      "مشاهدة 34,902",
    ],
    fourthSectionArticleTopRightParagraph: [
      "السعودية: إحباط تهريب أكثر من 3.2 مليون حبة كبتاغون",
      "مزاد على لوحات رسمها مصابون بالتوحد يجمع 6.5 مليون ريال",
      "السعودية: إحباط تهريب أكثر من 3.2 مليون حبة كبتاغون",
      "مزاد على لوحات رسمها مصابون بالتوحد يجمع 6.5 مليون ريال",
    ],
    fourthSectionArticleBottomTopParagraph: [
      "إصابة اثنين في حريق اندلع بناقلة وقود بالمدينة المنورة",
      "السعودية تدين بشدة محاولة اغتيال عمران خان",
      "إصابة اثنين في حريق اندلع بناقلة وقود بالمدينة المنورة",
      "السعودية تدين بشدة محاولة اغتيال عمران خان",
    ],
    navItemHeader: [
      "اخبار",
      "السعودية",
      "رياضة",
      "منوعات",
      "العربية TV",
      "مقالات",
      "الآخيرة",
      "بودكاست",
    ],
    embeddedNavItemLinks: [
      "العرب والعالم",
      "الخليج العربي",
      "رياضة",
      "سوريا",
      "مصر",
      "أميركا",
      "إيران",
      "العراق",
      "الأخبار",
      "نشرة الرابعة",
      "رياضة",
      "الآراء",
      "رياضة سعودية",
      "رياضة عربية",
      "رياضة عالمية",
      "رياضات أخرى",
      "الآراء",
      "صحة",
      "تكنولوجيا",
      "سوشيال ميديا",
      "ستايل",
      "علم",
      "فيديو العربية",
      "العربية ميديا",
      "برامج العربية",
      "آراء سياسية",
      "آراء رياضية",
      "آراء سعودية",
    ],
    upSpan: ["العودة إلى الأعلى"],
    copyRight: [" جميع الحقوق محفوظة لشبكة العربية - 2022 "],
  },
};
